### ISSUE TITLE
Update documentation to match new module names on nsecluster

### ISSUE THREAD

**Issue by gridley** [ustajan/grasshopper#18]
I'll submit a pull request at some point to update the documentation for using grasshopper on nsecluster. Ideally, I'd like to get people to run it through nsecluster.mit.edu/jhub/, which is dead simple to use.

Right now, a few things such as module names in the provided .bashrc file are out of date.

**Comment by ustajan** [comment]
I made the changes to the wiki.  .bashrc has been updated.
