### ISSUE TITLE
GNUmake does not work on WSLdue to lack of -lXi library

### ISSUE THREAD

**Issue by aamartz** [ustajan/grasshopper#20]
Upon using `make` when building in `/grasshopper` on WSL, there is the error output of:

`/usr/bin/ld: cannot find -lXi: No such file or directory`
`collect2: error: ld returned 1 exit status`

This can be solved by installing the libXi-devel (or equivalent) library:

`sudo apt-get install libxi-dev`

**Comment by ustajan** [comment]
Apologies for the late response, and thank you for the feedback. 

The issue you describe, nevertheless, is not grasshopper specific , but is rather related to the OS in question.
