### ISSUE TITLE
Cannot Find "G4IonPhysicsXS.hh"

### ISSUE THREAD

**Issue by eaklein** [ustajan/grasshopper#3]
Fatal error in compiling Grasshopper. Error finding "G4IonPhysicsXS.hh."
Grasshopper succesfully compiled when I commented out "G4IonPhysicsXS.hh" and used "G4IonPhysicsPHP.hh" instead.

**Comment by ustajan** [comment]
This is an incompatibility due to Geant4 version 10.6.  Stick to 10.5.
